// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckIPQuality(arg1:Array<string>):Promise<Array<models.IPQualityResult>>;

export function CheckWhois(arg1:Array<string>):Promise<Array<models.WhoisResult>>;

export function ParseInput(arg1:string):Promise<Record<string, any>>;
