// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIPQuality(arg1) {
  return window['go']['main']['App']['CheckIPQuality'](arg1);
}

export function CheckWhois(arg1) {
  return window['go']['main']['App']['CheckWhois'](arg1);
}

export function ParseInput(arg1) {
  return window['go']['main']['App']['ParseInput'](arg1);
}
